### ISSUE TITLE
get_cycle() in latency_test.c generate wrong machine code on SiFive E24

### ISSUE THREAD

**Issue by hotislandn** [sifive/benchmark-mem-test#1]
In the code, the hi, hi1, lo are defined as uint64_t. However, when compiled with riscv64-unknown-elf-gcc (SiFive GCC 8.3.0-2019.08.0), it generates wrong machine code on E24 (RISC-V 32bit core):

2201403e <get_cycle>:
     * it fails to handle the high 32bit of
     * uint64_t data. !!!
     */
    uint64_t hi, hi1, lo;

    __asm__ volatile("csrr %0, mcycleh" : "=r"(hi));
2201403e:	b8002773          	csrr	a4,mcycleh
    __asm__ volatile("csrr %0, mcycle" : "=r"(lo));
22014042:	b0002873          	csrr	a6,mcycle
    __asm__ volatile("csrr %0, mcycleh" : "=r"(hi1));
22014046:	b8002373          	csrr	t1,mcycleh
    if (hi == hi1) {
2201404a:	00670563          	beq	a4,t1,22014054 <get_cycle+0x16>
    uint64_t val = 0;
2201404e:	4501                	li	a0,0
22014050:	4581                	li	a1,0
    }
#else
    __asm__ volatile("csrr %0, mcycle" : "=r"(val));
#endif
    return val;
}
22014052:	8082                	ret
    if (hi == hi1) {
22014054:	fe779de3          	bne	a5,t2,2201404e <get_cycle+0x10>
        val = ((unsigned long long)hi << 32) | lo;
22014058:	8542                	mv	a0,a6
2201405a:	00e8e5b3          	or	a1,a7,a4
2201405e:	8082                	ret

You can see:
1. hi is a5:a4, hi1 is t2:t1
2. for the comparision of hi and hi1, it firstly compare the a4 vs t1, at address 2201404a. this is right
3. however, when it tries to compare the higher 32bit of uint64_t at address 22014054, this is wrong. Since in this function, a5 and t2 are not initialized, it contains the value from the caller. This lead to wrong behaviour of the program.

Now, change the data type to uint32_t fix this problem on E24.

**Comment by kayeoc279** [comment]
@hotislandn 
Thx for reporting this issue. 
What you said is correct, I should't use uint64_t to store 32-bit register result.
Let me know if there is other issue.

**Comment by kayeoc279** [comment]
@hotislandn 
we will use get_cycle api inside freedom-metal instead of the one created by me.
Anyway, thx for reporting this issue.

**Comment by hotislandn** [comment]
It's nothing.
